### ISSUE TITLE
Placement of root joint

### ISSUE THREAD

**Issue by nmansard** [humanoid-path-planner/hpp-model#28]
The currentTransformation of the rootJoint of a device initializaed with a "freeflyer" exhibits an identity rotation for a non-1,0,0,0 quaternion. Could you explain or check the behavior?

E.g. for romeo:
q = -0.541726    0.40124  -0.366266   0.533858  -0.436099  -0.691464   0.216079  -0.552687   0.302264  0.0213719   0.942931  -0.439916  0.0922138   0.438537  -0.773439 -0.0570331    0.18508   0.888636 -0.0981649  -0.327298   0.695369  -0.130973  -0.993537  -0.310114   0.196963   0.666487  -0.532217   0.350952 -0.0340994 -0.0361284  -0.390089   0.424175  -0.634888   0.243646  -0.918271  -0.172033   0.391968   0.347873

Placement from Pinocchio:
  R =
-0.0496261  0.372383 -0.926751
 0.833805  0.526255  0.166809
 0.549825 -0.764451 -0.336611
  p = -0.541726   0.40124 -0.366266

Placement from hpp::model
rotation matrix: [(1 0 0)(0 1 0)(0 0 1)]
rotation quaternion: (1, 0, 0, 0)
translation: (-0.541726 0.40124 -0.366266)

**Comment by jmirabel** [comment]
In HPP, a SE3 joint in implemented as 2 joints: R^3 then SO3. What you see
is the position of the R^3 joint.
The (normally unique) child joint of the root joint should be at the
expected position/orientation.

Joseph Mirabel
Le 6 juil. 2016 22:13, "Nicolas Mansard" <notifications@github.com> a
écrit :

The currentTransformation of the rootJoint of a device initializaed with a
"freeflyer" exhibits an identity rotation for a non-1,0,0,0 quaternion.
Could you explain or check the behavior?

E.g. for romeo:
q = -0.541726 0.40124 -0.366266 0.533858 -0.436099 -0.691464 0.216079
-0.552687 0.302264 0.0213719 0.942931 -0.439916 0.0922138 0.438537
-0.773439 -0.0570331 0.18508 0.888636 -0.0981649 -0.327298 0.695369
-0.130973 -0.993537 -0.310114 0.196963 0.666487 -0.532217 0.350952
-0.0340994 -0.0361284 -0.390089 0.424175 -0.634888 0.243646 -0.918271
-0.172033 0.391968 0.347873

Placement from Pinocchio:
R =
-0.0496261 0.372383 -0.926751
0.833805 0.526255 0.166809
0.549825 -0.764451 -0.336611
p = -0.541726 0.40124 -0.366266

Placement from hpp::model
rotation matrix: [(1 0 0)(0 1 0)(0 0 1)]
rotation quaternion: (1, 0, 0, 0)
translation: (-0.541726 0.40124 -0.366266)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/humanoid-path-planner/hpp-model/issues/28>, or mute the
thread
<https://github.com/notifications/unsubscribe/ACRw8aMEFZnRCC4oTYUTqjnsmOyTriDVks5qTAx0gaJpZM4JGdNw>
.

**Comment by nmansard** [comment]
So, having the root joint of a free flyer robot not rotating is a correct behavior? 
Is there any reason to try to keep the same behaviour in the new Pinocchio-based implementation?

**Comment by jmirabel** [comment]
It is the expected behaviour. We have not SE3 joint and we emulate it with
two joints.
The two first joints of HPP correspond together to the freefloating joint.
So the root joint always have no rotation in this case.

The influences of changing from R3+SO3 to SE3 I can think of are:
- locking a joint will be a little more tricky to implement but should be
feasible,
- what is the interpolation method for SE3 ? Are the linear and angular
part decoupled?
- weights of weighted Euclidean distance should not be the same for the
linear and the angular part.

**Comment by nmansard** [comment]
I understand that, but it was not my point. 
The actual behavior is that device->rootJoint->currentTransform is always a translation. I think it is counter-intuitive (root joint is in general rotation+translation). I then suspect that the method rootJoint is not used. 
Should I try to mimic this behavior? I would prefer not to.

**Comment by jmirabel** [comment]
I see your point. I cannot fully check right now but I think it's mostly
used to initialize a loop on the joint tree.
I don't think this behavior is a requirement at all. Pinocchio can ignore
it.

However, note that the root joint can be an anchor joint. This is a
requirement.
A possible alternative is to allow a device to have several root joints but
this  might be a too big design change for the task we aim at.

**Comment by florent-lamiraux** [comment]
In my opinion, we should not access a joint as the "root" joint unless we clearly target the first joint of the tree. Getting the freeflyer of a humanoid robot should be accessed by name. As mentioned by Joseph, in manipulation planning, the root joint is an anchor (or fixed joint).

**Comment by nmansard** [comment]
Ok. I do the most evident wrap. Let's see if it is enough, and think more otherwiste.
